# Generated by Django 3.0.7 on 2020-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now=True)),
                ('news_type', models.CharField(choices=[('adults', 'dospeli'), ('children', 'deti')], default='children', max_length=16)),
            ],
        ),
    ]
