# Generated by Django 3.0.7 on 2020-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_zpravy_cs', models.CharField(max_length=1000)),
                ('text_zpravy_en', models.CharField(default='Sorry, no translation available yet', max_length=1000)),
                ('datum', models.DateField(auto_now=True)),
                ('typ_aktualit', models.CharField(choices=[('adults', 'dospeli'), ('children', 'deti')], default='children', max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
