# Generated by Django 3.0.7 on 2020-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0002_auto_20200606_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='RozvrhDeti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.CharField(choices=[('mon', 'pondeli'), ('tue', 'utery'), ('wed', 'streda'), ('thu', 'ctvrtek'), ('fri', 'patek'), ('sat', 'sobota'), ('sun', 'nedele')], default='mon', max_length=16)),
                ('od', models.CharField(default='00:00', max_length=5)),
                ('do', models.CharField(default='00:00', max_length=5)),
                ('zaci_trida', models.CharField(default='1-2', max_length=20)),
                ('ucitel', models.CharField(default='Eva Lukášová', max_length=30)),
                ('max_kapacita_krouzku', models.IntegerField(default=10)),
            ],
        ),
    ]
