# Generated by Django 3.0.7 on 2020-06-09 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keramika_ostrovni_web', '0004_rozvrhdeti_cislo_krouzku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20)),
                ('prijmeni', models.CharField(max_length=20)),
                ('rocnik', models.IntegerField()),
                ('paralelka', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dospely',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20)),
                ('prijmeni', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dospeli', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Krouzek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_krouzku', models.IntegerField(default=100)),
                ('den', models.CharField(choices=[('mon', 'pondělí'), ('tue', 'úterý'), ('wed', 'středa'), ('thu', 'čtvrtek'), ('fri', 'pátek'), ('sat', 'sobota'), ('sun', 'neděle')], default='mon', max_length=16)),
                ('od', models.CharField(default='00:00', max_length=5)),
                ('do', models.CharField(default='00:00', max_length=5)),
                ('zaci_trida', models.CharField(default='1-2', max_length=20)),
                ('ucitel', models.CharField(default='Eva Lukášová', max_length=30)),
                ('max_kapacita_krouzku', models.IntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='RozvrhDeti',
        ),
        migrations.AddField(
            model_name='dite',
            name='krouzky',
            field=models.ManyToManyField(blank=True, related_name='zaci_krouzku', to='keramika_ostrovni_web.Krouzek'),
        ),
        migrations.AddField(
            model_name='dite',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deti', to=settings.AUTH_USER_MODEL),
        ),
    ]
