# Generated by Django 3.0.7 on 2020-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0005_auto_20200609_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='dite',
            name='ve_skolnim_roce',
            field=models.CharField(default=0.9995051954477981, max_length=9),
            preserve_default=False,
        ),
    ]
