# Generated by Django 3.0.7 on 2020-06-10 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keramika_ostrovni_web', '0006_dite_ve_skolnim_roce'),
    ]

    operations = [
        migrations.AddField(
            model_name='krouzek',
            name='cena',
            field=models.IntegerField(default=1800),
        ),
        migrations.CreateModel(
            name='PlatebniInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_uctu', models.CharField(default='0800/7625489755', max_length=50)),
                ('var_symbol', models.IntegerField(default=120)),
                ('suma_k_zaplaceni', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platebni_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KontaktInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(blank=True, max_length=20)),
                ('prijmeni', models.CharField(blank=True, max_length=20)),
                ('telefoni_cislo', models.IntegerField(blank=True)),
                ('email', models.EmailField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakt_info', to=settings.AUTH_USER_MODEL), max_length=254)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakt_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
