# Generated by Django 3.0.7 on 2020-06-10 12:05

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0008_auto_20200610_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontaktinfo',
            name='email',
            field=models.EmailField(default=django.contrib.auth.models.User, max_length=254),
        ),
    ]
