# Generated by Django 3.0.7 on 2020-06-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0010_auto_20200610_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontaktinfo',
            name='telefoni_cislo',
            field=models.IntegerField(blank=True, default=None, max_length=9, null=True),
        ),
    ]
