# Generated by Django 3.0.7 on 2020-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0012_auto_20200614_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='LekceDospeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_krouzku', models.IntegerField(default=900)),
                ('den', models.CharField(choices=[('mon', 'pondělí'), ('tue', 'úterý'), ('wed', 'středa'), ('thu', 'čtvrtek'), ('fri', 'pátek'), ('sat', 'sobota'), ('sun', 'neděle')], default='thu', max_length=16)),
                ('datum', models.DateField()),
                ('od', models.CharField(default='00:00', max_length=5)),
                ('do', models.CharField(default='00:00', max_length=5)),
                ('ucitel', models.CharField(default='Eva Lukášová', max_length=30)),
                ('max_kapacita_krouzku', models.IntegerField(default=10)),
                ('cena', models.IntegerField(default=100)),
            ],
        ),
    ]
