# Generated by Django 3.0.7 on 2020-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0013_lekcedospeli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dite',
            old_name='krouzky',
            new_name='zapsany_krouzek',
        ),
        migrations.AddField(
            model_name='dite',
            name='zapsany_JN_krouzek',
            field=models.ManyToManyField(blank=True, related_name='nahradnici_krouzku', to='keramika_ostrovni_web.Krouzek'),
        ),
    ]
