# Generated by Django 3.0.7 on 2020-08-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0014_auto_20200824_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='dite',
            name='poradi_nahradnika',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.AddField(
            model_name='krouzek',
            name='konec_fronty',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.AddField(
            model_name='krouzek',
            name='start_fronty',
            field=models.IntegerField(default=0, max_length=9),
        ),
    ]
