# Generated by Django 3.0.7 on 2020-08-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0015_auto_20200825_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dite',
            name='poradi_nahradnika',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='krouzek',
            name='konec_fronty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='krouzek',
            name='start_fronty',
            field=models.IntegerField(default=0),
        ),
    ]
