# Generated by Django 3.1 on 2021-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keramika_ostrovni_web', '0016_auto_20200825_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuality',
            name='barva_textu',
            field=models.CharField(choices=[('black', 'black'), ('red', 'red')], default='black', max_length=16),
        ),
        migrations.AlterField(
            model_name='krouzek',
            name='cena',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='lekcedospeli',
            name='cislo_krouzku',
            field=models.IntegerField(default=9000),
        ),
        migrations.AlterField(
            model_name='lekcedospeli',
            name='do',
            field=models.CharField(default='19:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='lekcedospeli',
            name='od',
            field=models.CharField(default='16:00', max_length=5),
        ),
    ]
